name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and test job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t media-service:latest .
    
  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh khangduong@ssh.khangduong.me -p 443 "
        cd /app &&
        git pull origin main &&
        docker build -t media-service:latest . &&
        docker stop media-service || true &&
        docker rm media-service || true &&
        docker run -d --name media-service -p 3000:3000 media-service:latest &&
        pm2 reload ecosystem.config.js --env production
        "
